# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

train_Rcpp <- function(numberOfChildrenperNode, treeHeight, initialLearningRate, finalLearningRate, initialRadius, finalRadius, iterations, lst, Names = as.character( c())) {
    .Call('BKTSOM_train_Rcpp', PACKAGE = 'BKTSOM', numberOfChildrenperNode, treeHeight, initialLearningRate, finalLearningRate, initialRadius, finalRadius, iterations, lst, Names)
}

FindBMU <- function(listNeuron, stimulus) {
    .Call('BKTSOM_FindBMU', PACKAGE = 'BKTSOM', listNeuron, stimulus)
}

rcpp_hello <- function() {
    .Call('BKTSOM_rcpp_hello', PACKAGE = 'BKTSOM')
}

